name: Run Postman Collection Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js (v18)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman 

      - name: AdmissionCriteria
        # Continue even if the newman command fails (test failures)
        env:
          TOKEN: ${{ secrets.TOKEN }} # Inject secret token
          URL: ${{ secrets.URL }}
        run: |
          newman run AdmissionCriteria.json --reporters cli,junit \
          --env-var "url=$URL" \
          --env-var "token=$TOKEN" \
          --reporter-junit-export AdmissionCriteria.xml
        continue-on-error: true  

      - name: Upload JUnit report for AdmissionCriteria
        uses: actions/upload-artifact@v3
        with:
          name: AdmissionCriteria
          path: AdmissionCriteria.xml
          
      - name: Country
        # Continue even if the newman command fails (test failures)
        env:
          TOKEN: ${{ secrets.TOKEN }} # Inject secret token
          URL: ${{ secrets.URL }}
        run: |
          newman run Country.json --reporters cli,junit \
          --env-var "url=$URL" \
          --env-var "token=$TOKEN" \
          --reporter-junit-export Country.xml
        continue-on-error: true  

      - name: Upload JUnit report for Country
        uses: actions/upload-artifact@v3
        with:
          name: Country
          path: Country.xml

      - name: CourseTime
        # Continue even if the newman command fails (test failures)
        env:
          TOKEN: ${{ secrets.TOKEN }} # Inject secret token
          URL: ${{ secrets.URL }}
        run: |
          newman run CourseTime.json --reporters cli,junit \
          --env-var "url=$URL" \
          --env-var "token=$TOKEN" \
          --reporter-junit-export CourseTime.xml
        continue-on-error: true  

      - name: Upload JUnit report for CourseTime
        uses: actions/upload-artifact@v3
        with:
          name: CourseTime
          path: CourseTime.xml    
