name: Run Postman Collection Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js (v18)
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Install Newman
        run: npm install -g newman newman-reporter-html newman-reporter-junit

      - name: Run Postman collection with report
        # Continue even if the newman command fails (test failures)
        env:
          POSTMAN_TOKEN: ${{ secrets.POSTMAN_TOKEN }} # This injects the secret token
        run: |
          newman run CourseTime.json \
          --env-var "token=$POSTMAN_TOKEN" \
          --reporter-junit-export ./CourseTimereport.xml
        continue-on-error: true  

      - name: Upload JUnit report
        uses: actions/upload-artifact@v3
        with:
          name: junit-report
          path: CourseTimereport.xml
          
      - name: Run Postman collection with report
        # Continue even if the newman command fails (test failures)
        env:
          POSTMAN_TOKEN: ${{ secrets.POSTMAN_TOKEN }} # This injects the secret token
        run: |
          newman run CourseType.json \
          --env-var "token=$POSTMAN_TOKEN" \
          --reporter-junit-export ./CourseTypereport.xml
        continue-on-error: true    

      - name: Upload JUnit report
        uses: actions/upload-artifact@v3
        with:
          name: junit-report
          path: CourseTypereport.xml
             
