name: Run Postman Collection Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js (v18)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman 

      - name: Run Postman collection with report 
        # Continue even if the newman command fails (test failures)
        env:
          POSTMAN_TOKEN: ${{ secrets.POSTMAN_TOKEN }} # Inject secret token
        run: |
          newman run CourseTime.json --reporters cli,junit \
          --env-var "token=$POSTMAN_TOKEN" \
          --reporter-junit-export newman-report.xml
          ls -la
        continue-on-error: true  

      - name: Upload JUnit report for CourseTime
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: newman-report.xml
          
      - name: Run Postman collection with report 
        # Continue even if the newman command fails (test failures)
        env:
          POSTMAN_TOKEN: ${{ secrets.POSTMAN_TOKEN }} # Inject secret token
        run: |
          newman run CourseType.json --reporters cli,junit \
          --env-var "token=$POSTMAN_TOKEN" \
          --reporter-junit-export newman-report1.xml
          ls -la
        continue-on-error: true  

      - name: Upload JUnit report for CourseTime
        uses: actions/upload-artifact@v3
        with:
          name: newman-report1
          path: newman-report1.xml
