name: Run Postman Collection Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js (v18)
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman collection with report
        # Continue even if the newman command fails (test failures)
        run: |
          newman run CourseTime.json --reporters cli,junit \
          --reporter-junit-export newman-report.xml
        continue-on-error: true  # Allow failure but continue the workflow

      - name: Upload Newman report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: newman-report.xml
